name: playerLives
main: com.pathogenstudios.playerlives.playerLives
version: 1.4.1
author: Pathogen_David

commands:
    lives:
        description: Show the number of lives you or others have.
        usage: |
               /<command>
               Example: /<command> | Display your number of lives
               Example: /<command> [player] | Dispaly the number of lives [player] has
    givelives:
        aliases: [givelife]
        description: Gives you or others more lives
        usage: |
               /<command>
               Example: /<command> [player] [count] | Give [player] [count] lives
    takelives:
        aliases: [takelife]
        description: Takes lives from you or others
        usage: |
               /<command>
               Example: /<command> [player] [count] | Take [count] lives from [player]
    setlives:
        description: Sets your or other's life count
        usage: |
               /<command>
               Example: /<command> [player] [count] | Set [player]'s lives to [count]
    buylives:
        aliases: [buylife]
        description: Buy more lives for yourself
        usage: |
               /<command> [count]
               Example: /<command> [count] | Buy [count] lives for yourself